### ISSUE TITLE
Ryoshima Coast Not playing music while paintbrush is out

### ISSUE THREAD

**Issue by chadstir95** [Auride/okami-disable-brush-music#1]
First off, thank you so much for making this mod! I am playing through for the first time and the paintbrush music interrupting the fantastic soundtrack bothered me to the point of making me stop playing on my PS4 so I am now loving this game. 

Now that the Rant is over the music to Ryoshima Coast will not play when the paintbrush is out it will not play the paintbrush theme either, now I did just get to this area so if the theme changes at some point here, that could be causing the problem but I don't know if that is a factor. so it is just silent, was hoping you could try and look into this? 

thank you!

**Comment by Auride** [comment]
Thank you for reporting this. I was able to replicate it. I fixed this in version 1.1.0, available here: https://github.com/Auride/okami-disable-brush-music/releases/tag/v1.1.0

Please let me know if you find any more issues.

**Comment by chadstir95** [comment]
Will do for reporting more issues, I know I said in the post but thankyou
again for making this mod!
